/**
 * SIH Artisan Project — Mock Data Layer
 * 
 * TODO: integrate with backend
 * All data access functions here provide mock JSON responses.
 * When backend APIs are ready, Person 3 (Backend) can replace these functions
 * with real fetch/Axios calls without modifying component internals.
 */

export const mockArtisans = [
  {
    id: 'artisan-1',
    name: 'Govindappa V.',
    specialty: 'Kalamkari Hand Painting',
    region: 'Srikalahasti, Andhra Pradesh',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
    bio: 'Fourth-generation Kalamkari master craftsman specializing in natural vegetable dyes and freehand bamboo pen drawing depicting ancient epics.',
    experienceYears: 32,
    rating: 4.9,
    reviewCount: 128,
    productsCount: 14,
    tags: ['Kalamkari', 'Natural Dyes', 'Tamarind Pen', 'GI Certified'],
  },
  {
    id: 'artisan-2',
    name: 'Kripal Singh Kripal',
    specialty: 'Jaipur Blue Pottery',
    region: 'Jaipur, Rajasthan',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    bio: 'Preserving the Persian-origin quartz-based pottery tradition of Rajasthan, crafted without clay using quartz stone powder, Fuller’s earth, and natural gum.',
    experienceYears: 28,
    rating: 4.85,
    reviewCount: 96,
    productsCount: 18,
    tags: ['Blue Pottery', 'Quartz Dough', 'Lead-Free Glaze', 'Heritage Awardee'],
  },
  {
    id: 'artisan-3',
    name: 'Rashida Begum',
    specialty: 'Pashmina & Sozni Embroidery',
    region: 'Srinagar, Kashmir',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    bio: 'Leading a cooperative of 25 women artisans in Old Srinagar practicing needlepoint Sozni embroidery on authentic hand-spun Changthangi goat wool.',
    experienceYears: 24,
    rating: 4.95,
    reviewCount: 210,
    productsCount: 11,
    tags: ['Pashmina', 'Sozni Needlework', 'Changthangi Wool', 'GI Tagged'],
  },
  {
    id: 'artisan-4',
    name: 'Devanand Acharya',
    specialty: 'Dhokra Lost-Wax Bell Metal',
    region: 'Bastar, Chhattisgarh',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    bio: 'Practicing a 4,000-year-old non-ferrous metal casting technique handed down through generations of tribal metal smiths.',
    experienceYears: 19,
    rating: 4.78,
    reviewCount: 74,
    productsCount: 9,
    tags: ['Dhokra', 'Lost Wax', 'Bell Metal', 'Tribal Heritage'],
  },
];

export const mockProducts = [
  {
    id: 'prod-1',
    title: 'Hand-Painted Tree of Life Kalamkari Wall Hanging',
    artisanId: 'artisan-1',
    artisanName: 'Govindappa V.',
    price: 3450,
    originalPrice: 4200,
    rating: 4.9,
    reviewCount: 42,
    images: [
      'https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800',
    ],
    craft: 'Kalamkari',
    technique: 'Freehand Bamboo Pen & Mordant Dyeing',
    material: 'Organic Khadi Cotton & Vegetable Dyes',
    region: 'Andhra Pradesh',
    season: 'Autumn / Festival',
    description: 'Rendered in classic Srikalahasti style using fermented jaggery, alum mordants, and buffalo milk treatment. Each line is drawn using a bamboo reed pen (kalam).',
    inStock: 6,
    storyExcerpt: 'The Tree of Life (Kalpavriksha) symbolizes the eternal interconnectedness of living beings in traditional folklore.',
  },
  {
    id: 'prod-2',
    title: 'Traditional Floral Motifs Blue Pottery Serving Bowl',
    artisanId: 'artisan-2',
    artisanName: 'Kripal Singh Kripal',
    price: 1850,
    originalPrice: 2200,
    rating: 4.8,
    reviewCount: 31,
    images: [
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&q=80&w=800',
    ],
    craft: 'Blue Pottery',
    technique: 'Low-Fire Quartz Moulding & Hand Glazing',
    material: 'Quartz Powder, Fuller Earth & Copper Oxide',
    region: 'Rajasthan',
    season: 'All Season',
    description: 'Authentic Jaipur Blue Pottery handcrafted without clay. The signature turquoise color is achieved using natural copper oxide pigments fired in open kilns.',
    inStock: 12,
    storyExcerpt: 'Turquoise shades were originally brought to Rajasthan by royal courts from Turko-Persian traditions in the 14th century.',
  },
  {
    id: 'prod-3',
    title: 'Pure Cashmere Sozni Embroidered Floral Stole',
    artisanId: 'artisan-3',
    artisanName: 'Rashida Begum',
    price: 12500,
    originalPrice: 15000,
    rating: 5.0,
    reviewCount: 68,
    images: [
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&q=80&w=800',
    ],
    craft: 'Pashmina Weaving',
    technique: 'Fine Sozni Needlework & Handloom Weave',
    material: '100% Changthangi Goat Cashmere & Silk Floss',
    region: 'Kashmir',
    season: 'Winter & Autumn',
    description: 'Spun from grade-A Ladakh Changthangi mountain goat cashmere under 15 microns. Delicate floral border needlepoint takes over 180 hours of patient handwork.',
    inStock: 3,
    storyExcerpt: 'Passed down from Sufi poet-saints, the motifs depict almond blossoms (badam) celebrating spring in the Kashmir valley.',
  },
  {
    id: 'prod-4',
    title: 'Bastar Tribal Bison Horn Dancer Dhokra Figurine',
    artisanId: 'artisan-4',
    artisanName: 'Devanand Acharya',
    price: 2600,
    originalPrice: 3100,
    rating: 4.7,
    reviewCount: 19,
    images: [
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=800',
    ],
    craft: 'Dhokra Metal Casting',
    technique: 'Cire Perdue (Lost-Wax Casting)',
    material: 'Recycled Bell Metal & Bee Wax',
    region: 'Chhattisgarh',
    season: 'All Season',
    description: 'An ancient lost-wax brass sculpture honoring the Maria tribal dancers. Every piece is unique because the clay mould is broken during the casting process.',
    inStock: 8,
    storyExcerpt: 'Lost-wax casting has survived in the tribal heartland of India since the dancing girl of Mohenjo-daro.',
  },
  {
    id: 'prod-5',
    title: 'Natural Indigo Handblock Print Chanderi Silk Saree',
    artisanId: 'artisan-1',
    artisanName: 'Govindappa V.',
    price: 6800,
    originalPrice: 8500,
    rating: 4.9,
    reviewCount: 54,
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
    ],
    craft: 'Dabu Block Printing',
    technique: 'Mud-Resist Dabu & Handloom Weave',
    material: 'Chanderi Silk Cotton & Organic Indigo',
    region: 'Rajasthan',
    season: 'Festive / Spring',
    description: 'Clay-resist block printing dipped in subterranean indigo fermentation vats. Feather-light drape woven with real zari borders.',
    inStock: 5,
    storyExcerpt: 'Dabu mud resist creates characteristic crackle veins as the mud dries under the desert sun.',
  },
  {
    id: 'prod-6',
    title: 'Bidriware Silver Inlaid Floral Trinket Box',
    artisanId: 'artisan-2',
    artisanName: 'Kripal Singh Kripal',
    price: 4100,
    originalPrice: 4800,
    rating: 4.85,
    reviewCount: 27,
    images: [
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=800',
    ],
    craft: 'Bidriware',
    technique: 'Zinc-Copper Alloy Inlay & Soil Oxidation',
    material: 'Zinc Alloy, Pure Silver Wire & Fort Soil',
    region: 'Karnataka',
    season: 'All Season',
    description: 'Pure silver wire hammered into etched zinc-copper alloy, blackened using historic soil from Bidar Fort containing unique oxidizing salts.',
    inStock: 4,
    storyExcerpt: 'The soil of Bidar Fort has unique natural chemistry that reacts with zinc to turn it deep velvet black while leaving silver gleaming.',
  },
];

export const mockStories = [
  {
    id: 'story-1',
    title: 'The Ink That Never Fades: Secrets of Srikalahasti Kalamkari',
    artisanName: 'Govindappa V.',
    artisanId: 'artisan-1',
    craft: 'Kalamkari',
    region: 'Andhra Pradesh',
    image: 'https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&q=80&w=800',
    readTime: '4 min read',
    excerpt: 'Deep in the Chittoor district along the Swarnamukhi river, master painters use buffalo milk, fermented jaggery, and crushed madder roots to craft art that breathes with sacred geometry.',
    quote: '"Our kalam does not just lay ink; it tells the prayer of our ancestors on unbleached cotton."',
  },
  {
    id: 'story-2',
    title: 'Born From Clay-Free Earth: The Jaipur Blue Pottery Renaissance',
    artisanName: 'Kripal Singh Kripal',
    artisanId: 'artisan-2',
    craft: 'Blue Pottery',
    region: 'Rajasthan',
    image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&q=80&w=800',
    readTime: '6 min read',
    excerpt: 'Unlike terracotta or porcelain, Jaipur Blue Pottery contains zero clay. It is crafted from powdered quartz, glass, and Multani Mitti, surviving kiln fires through ancestral patience.',
    quote: '"When the copper oxide meets the low fire, the blue that emerges is the color of the desert sky after rain."',
  },
  {
    id: 'story-3',
    title: 'The 14-Micron Thread: Himalayan Nomads and Srinagar Looms',
    artisanName: 'Rashida Begum',
    artisanId: 'artisan-3',
    craft: 'Pashmina',
    region: 'Kashmir',
    image: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&q=80&w=800',
    readTime: '5 min read',
    excerpt: 'At 14,000 feet on the windswept plains of Changthang, the Changpa nomads harvest the winter underfleece of capra hircus goats — fleece so fine only human hands can spin it.',
    quote: '"Each stitch of Sozni is a quiet conversation between the weaver and the mountain cold."',
  },
];

export const mockCraftGraphNodes = [
  { id: 'craft-1', type: 'Craft', label: 'Kalamkari Painting', count: 18, color: '#B5502E' },
  { id: 'tech-1', type: 'Technique', label: 'Bamboo Reed Pen (Kalam)', count: 12, color: '#7A6A3F' },
  { id: 'tech-2', type: 'Technique', label: 'Natural Mordant Dyeing', count: 15, color: '#7A6A3F' },
  { id: 'mat-1', type: 'Material', label: 'Organic Khadi Cotton', count: 24, color: '#2F5D50' },
  { id: 'mat-2', type: 'Material', label: 'Fermented Jaggery & Iron Rust', count: 8, color: '#2F5D50' },
  { id: 'reg-1', type: 'Region', label: 'Srikalahasti, Andhra Pradesh', count: 14, color: '#2E5F8A' },
  { id: 'story-node-1', type: 'Cultural Story', label: 'Swarnamukhi River Heritage', count: 3, color: '#C08A1E' },
  { id: 'season-1', type: 'Season', label: 'Autumn / Deepavali', count: 35, color: '#3D7A4C' },
  { id: 'trend-1', type: 'Market Trend', label: 'Sustainable Eco-Home Decor (+42%)', count: 90, color: '#B23A34' },
];

export const mockOrders = [
  {
    id: 'ORD-8941',
    customerName: 'Aarav Sharma',
    customerEmail: 'aarav.sharma@example.com',
    productTitle: 'Hand-Painted Tree of Life Kalamkari Wall Hanging',
    artisanName: 'Govindappa V.',
    date: '2026-09-02',
    total: 3450,
    status: 'Delivered',
    paymentStatus: 'Paid',
    itemsCount: 1,
  },
  {
    id: 'ORD-8942',
    customerName: 'Meera Nambiar',
    customerEmail: 'meera.n@example.com',
    productTitle: 'Floral Motifs Blue Pottery Serving Bowl',
    artisanName: 'Kripal Singh Kripal',
    date: '2026-09-04',
    total: 3700,
    status: 'Processing',
    paymentStatus: 'Paid',
    itemsCount: 2,
  },
  {
    id: 'ORD-8943',
    customerName: 'Karan Sen',
    customerEmail: 'karan.sen@example.com',
    productTitle: 'Pure Cashmere Sozni Embroidered Floral Stole',
    artisanName: 'Rashida Begum',
    date: '2026-09-05',
    total: 12500,
    status: 'Shipped',
    paymentStatus: 'Paid',
    itemsCount: 1,
  },
  {
    id: 'ORD-8944',
    customerName: 'Priya Mukherjee',
    customerEmail: 'priya.m@example.com',
    productTitle: 'Bastar Tribal Bison Horn Dancer Dhokra Figurine',
    artisanName: 'Devanand Acharya',
    date: '2026-09-06',
    total: 2600,
    status: 'Pending',
    paymentStatus: 'Awaiting Confirmation',
    itemsCount: 1,
  },
];

export const mockInventory = [
  {
    id: 'inv-1',
    sku: 'KALAM-001',
    productTitle: 'Hand-Painted Tree of Life Wall Hanging',
    craft: 'Kalamkari',
    stock: 6,
    reorderThreshold: 5,
    status: 'Low Stock',
    unitPrice: 3450,
  },
  {
    id: 'inv-2',
    sku: 'BP-042',
    productTitle: 'Floral Motifs Blue Pottery Serving Bowl',
    craft: 'Blue Pottery',
    stock: 18,
    reorderThreshold: 8,
    status: 'In Stock',
    unitPrice: 1850,
  },
  {
    id: 'inv-3',
    sku: 'PASH-011',
    productTitle: 'Pure Cashmere Sozni Embroidered Stole',
    craft: 'Pashmina',
    stock: 2,
    reorderThreshold: 4,
    status: 'Critically Low',
    unitPrice: 12500,
  },
  {
    id: 'inv-4',
    sku: 'DHOK-088',
    productTitle: 'Bastar Tribal Bison Horn Dancer Figurine',
    craft: 'Dhokra',
    stock: 14,
    reorderThreshold: 6,
    status: 'In Stock',
    unitPrice: 2600,
  },
];

export const mockArtisanStats = {
  totalRevenue: 148500,
  revenueTrend: '+18.4%',
  totalOrders: 47,
  ordersTrend: '+12.0%',
  craftGraphViews: 1240,
  graphViewsTrend: '+34.5%',
  customerRating: 4.92,
  ratingTrend: '+0.1',
};

export const mockAdminStats = {
  activeArtisans: 142,
  artisansTrend: '+8.2%',
  catalogProducts: 1860,
  productsTrend: '+15.4%',
  monthlyVolume: 1845000,
  volumeTrend: '+22.1%',
  craftTraditionsPreserved: 38,
  traditionsTrend: '+3 new',
};

export const mockReviews = [
  {
    id: 'rev-1',
    userName: 'Pooja Iyer',
    rating: 5,
    date: '2026-08-28',
    comment: 'The vegetable dye aroma and the fine pen lines on this Kalamkari piece are breathtaking. It truly feels like holding history.',
    verifiedPurchase: true,
  },
  {
    id: 'rev-2',
    userName: 'David Miller',
    rating: 5,
    date: '2026-08-20',
    comment: 'Arrived packed with such care, along with the story card from the artisan. The turquoise glaze on the bowl has incredible depth.',
    verifiedPurchase: true,
  },
];

// TODO: integrate with backend
export const fetchProducts = () => Promise.resolve(mockProducts);
export const fetchProductById = (id) => Promise.resolve(mockProducts.find((p) => p.id === id) || mockProducts[0]);
export const fetchArtisans = () => Promise.resolve(mockArtisans);
export const fetchArtisanById = (id) => Promise.resolve(mockArtisans.find((a) => a.id === id) || mockArtisans[0]);
export const fetchOrders = () => Promise.resolve(mockOrders);
export const fetchInventory = () => Promise.resolve(mockInventory);
export const fetchStories = () => Promise.resolve(mockStories);
